import { Inter } from 'next/font/google'
import './globals.css'
import Header from '../components/header/Header'
import Trending from '../components/trending/Trending'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Movies',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <div className='px-5 xl:px-20 '>
          <Trending />
        </div>
        {children}
      </body>
    </html>
  )
}
