import { Inter } from 'next/font/google'
import './globals.css'
import Header from '../components/header/header'
import Trending from '../components/trending/trending'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Movies',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <Trending />
        {children}
      </body>
    </html>
  )
}
